name: GitHub Contribution Snake

on:
  push:
    branches:
      - main   # Ana branch’in adı
  workflow_dispatch: # Manuel çalıştırmak için

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: platane/snk@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_path: ./output/snake.svg

      - name: Commit & Push Snake
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output/snake.svg
          git commit -m "Update contribution snake"
          git push origin output
